; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = XiaoNRF52840

[env:XiaoNRF52840]
; Xiao nRF52840のボード定義は本家platformio/platform-nordicnrf52に未マージ
; (https://github.com/platformio/platform-nordicnrf52/pull/151, Open状態)のため、
; コミュニティで広く使われているフォークを使用する
platform = https://github.com/maxgerhardt/platform-nordicnrf52.git
; xiaoble_adafruit: Adafruit nRF52 Arduinoコアベース。標準WireライブラリでI2C Slaveが
; 公式サポートされている点、BLE Central(Bluefruit52Lib)の実績が豊富な点を理由に選定
; (mbedコア版のxiaobleはI2Cスレーブ対応が弱いため不採用。詳細はREADME参照)
board = xiaoble_adafruit
framework = arduino
build_type = debug
monitor_filters = time
monitor_speed = 115200
lib_deps =
